version: "2"

run:
  timeout: 5m

linters:
  disable:
    - all
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - deadcode
    - gosimple
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
