package cloudmetrics

import (
	"context"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"go.uber.org/zap"
)

// CloudMetrics emits Railzway Cloud platform usage accounting signals from OSS components.
// These metrics are for Railzway Cloud accounting only; they must never be used for billing,
// rating, invoice, or ledger calculation.
type CloudMetrics struct {
	registry            *prometheus.Registry
	pusher              Pusher
	usageEvents         *prometheus.CounterVec
	invoicesGenerated   *prometheus.CounterVec
	activeSubscriptions *prometheus.GaugeVec
	engineErrors        *prometheus.CounterVec
	pulse               *prometheus.GaugeVec
	organizationsTotal  *prometheus.GaugeVec
	usageLateEvents     *prometheus.CounterVec
	schedulerDuration   *prometheus.GaugeVec
	memoryUsage         *prometheus.GaugeVec
	instanceID          string
	version             string
	logger              *zap.Logger
}

// New registers Cloud metrics on the provided registry and returns a CloudMetrics handle.
func New(registry *prometheus.Registry, pusher Pusher, instanceID string, version string, logger *zap.Logger) *CloudMetrics {
	if registry == nil {
		registry = prometheus.NewRegistry()
	}
	if logger == nil {
		logger = zap.NewNop()
	}

	commonLabels := []string{"org", "instance_id", "version"}

	usageEvents := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "railzway_cloud_usage_events_emitted_total",
		Help: "Cloud accounting: usage events emitted by OSS workflows.",
	}, append(commonLabels, "meter"))

	invoicesGenerated := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "railzway_cloud_invoices_generated_total",
		Help: "Cloud accounting: invoices generated by OSS workflows.",
	}, commonLabels)

	activeSubscriptions := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "railzway_cloud_active_subscriptions",
		Help: "Cloud accounting: active subscriptions tracked by OSS workflows.",
	}, commonLabels)

	engineErrors := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "railzway_cloud_engine_errors_total",
		Help: "Cloud accounting: OSS workflow errors by operation.",
	}, append(commonLabels, "operation"))

	pulse := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "railzway_cloud_pulse",
		Help: "Cloud accounting: startup pulse metric.",
	}, commonLabels)

	organizationsTotal := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "railzway_cloud_organizations_total",
		Help: "Cloud accounting: total number of organizations.",
	}, commonLabels)

	usageLateEvents := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "railzway_cloud_usage_late_events_total",
		Help: "Cloud accounting: total number of usage events that arrived late.",
	}, append(commonLabels, "meter"))

	schedulerDuration := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "railzway_cloud_scheduler_job_duration_seconds",
		Help: "Cloud accounting: duration of the last successful scheduler job.",
	}, append(commonLabels, "job"))

	memoryUsage := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "railzway_cloud_system_memory_rss_bytes",
		Help: "Cloud accounting: current memory resident set size (RSS).",
	}, commonLabels)

	registry.MustRegister(usageEvents, invoicesGenerated, activeSubscriptions, engineErrors, pulse,
		organizationsTotal, usageLateEvents, schedulerDuration, memoryUsage)

	// Initialize pulse
	pulse.WithLabelValues("system", instanceID, version).Set(1)

	return &CloudMetrics{
		registry:            registry,
		pusher:              pusher,
		usageEvents:         usageEvents,
		invoicesGenerated:   invoicesGenerated,
		activeSubscriptions: activeSubscriptions,
		engineErrors:        engineErrors,
		pulse:               pulse,
		organizationsTotal:  organizationsTotal,
		usageLateEvents:     usageLateEvents,
		schedulerDuration:   schedulerDuration,
		memoryUsage:         memoryUsage,
		instanceID:          instanceID,
		version:             version,
		logger:              logger,
	}
}

// IncUsageEvent records an emitted usage event for Cloud accounting.
func (c *CloudMetrics) IncUsageEvent(org, meter string) {
	if c == nil || c.usageEvents == nil {
		return
	}
	c.usageEvents.WithLabelValues(normalizeOrg(org), c.instanceID, c.version, normalizeLabel(meter)).Inc()
}

// IncInvoiceGenerated records an emitted invoice for Cloud accounting.
func (c *CloudMetrics) IncInvoiceGenerated(org string) {
	if c == nil || c.invoicesGenerated == nil {
		return
	}
	c.invoicesGenerated.WithLabelValues(normalizeOrg(org), c.instanceID, c.version).Inc()
}

// SetActiveSubscriptions updates the active subscription gauge for Cloud accounting.
func (c *CloudMetrics) SetActiveSubscriptions(org string, count int) {
	if c == nil || c.activeSubscriptions == nil {
		return
	}
	if count < 0 {
		count = 0
	}
	c.activeSubscriptions.WithLabelValues(normalizeOrg(org), c.instanceID, c.version).Set(float64(count))
}

// IncEngineError records a billing workflow error for Cloud accounting.
func (c *CloudMetrics) IncEngineError(org, operation string) {
	if c == nil || c.engineErrors == nil {
		return
	}
	c.engineErrors.WithLabelValues(normalizeOrg(org), c.instanceID, c.version, normalizeLabel(operation)).Inc()
}

// SetOrganizationsTotal updates the total organizations gauge for Cloud accounting.
func (c *CloudMetrics) SetOrganizationsTotal(count int64) {
	if c == nil || c.organizationsTotal == nil {
		return
	}
	c.organizationsTotal.WithLabelValues("system", c.instanceID, c.version).Set(float64(count))
}

// IncUsageLateEvent records a late usage event for Cloud accounting.
func (c *CloudMetrics) IncUsageLateEvent(org, meter string) {
	if c == nil || c.usageLateEvents == nil {
		return
	}
	c.usageLateEvents.WithLabelValues(normalizeOrg(org), c.instanceID, c.version, normalizeLabel(meter)).Inc()
}

// SetSchedulerJobDuration records the duration of a scheduler job for Cloud accounting.
func (c *CloudMetrics) SetSchedulerJobDuration(job string, duration time.Duration) {
	if c == nil || c.schedulerDuration == nil {
		return
	}
	c.schedulerDuration.WithLabelValues("system", c.instanceID, c.version, normalizeLabel(job)).Set(duration.Seconds())
}

// SetMemoryUsage updates the system memory RSS gauge for Cloud accounting.
func (c *CloudMetrics) SetMemoryUsage(rss uint64) {
	if c == nil || c.memoryUsage == nil {
		return
	}
	c.memoryUsage.WithLabelValues("system", c.instanceID, c.version).Set(float64(rss))
}

// Push sends metrics via the configured pusher. Callers must invoke this explicitly.
func (c *CloudMetrics) Push(ctx context.Context) error {
	if c == nil || c.registry == nil {
		return nil
	}
	if c.pusher == nil {
		c.logger.Info("skipping cloud metrics push: telemetry pusher not initialized (check CLOUD_METRICS_ENDPOINT)")
		return nil
	}
	if ctx == nil {
		ctx = context.Background()
	}
	return c.pusher.Push(ctx, c.registry)
}

func normalizeOrg(org string) string {
	org = strings.TrimSpace(org)
	if org == "" {
		return "unknown"
	}
	return org
}

func normalizeLabel(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "unknown"
	}
	return value
}
