package cloudmetrics

import (
	"context"
	"strings"

	"github.com/prometheus/client_golang/prometheus"
)

// CloudMetrics emits Valora Cloud platform usage accounting signals from OSS components.
// These metrics are for Valora Cloud accounting only; they must never be used for billing,
// rating, invoice, or ledger calculation.
type CloudMetrics struct {
	registry            *prometheus.Registry
	pusher              Pusher
	usageEvents         *prometheus.CounterVec
	invoicesGenerated   *prometheus.CounterVec
	activeSubscriptions *prometheus.GaugeVec
	engineErrors        *prometheus.CounterVec
}

// New registers Cloud metrics on the provided registry and returns a CloudMetrics handle.
func New(registry *prometheus.Registry, pusher Pusher) *CloudMetrics {
	if registry == nil {
		registry = prometheus.NewRegistry()
	}

	usageEvents := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "valora_cloud_usage_events_emitted_total",
		Help: "Cloud accounting: usage events emitted by OSS workflows.",
	}, []string{"org", "meter"})

	invoicesGenerated := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "valora_cloud_invoices_generated_total",
		Help: "Cloud accounting: invoices generated by OSS workflows.",
	}, []string{"org"})

	activeSubscriptions := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "valora_cloud_active_subscriptions",
		Help: "Cloud accounting: active subscriptions tracked by OSS workflows.",
	}, []string{"org"})

	engineErrors := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "valora_cloud_engine_errors_total",
		Help: "Cloud accounting: OSS workflow errors by operation.",
	}, []string{"org", "operation"})

	registry.MustRegister(usageEvents, invoicesGenerated, activeSubscriptions, engineErrors)

	return &CloudMetrics{
		registry:            registry,
		pusher:              pusher,
		usageEvents:         usageEvents,
		invoicesGenerated:   invoicesGenerated,
		activeSubscriptions: activeSubscriptions,
		engineErrors:        engineErrors,
	}
}

// IncUsageEvent records an emitted usage event for Cloud accounting.
func (c *CloudMetrics) IncUsageEvent(org, meter string) {
	if c == nil || c.usageEvents == nil {
		return
	}
	c.usageEvents.WithLabelValues(normalizeOrg(org), normalizeLabel(meter)).Inc()
}

// IncInvoiceGenerated records an emitted invoice for Cloud accounting.
func (c *CloudMetrics) IncInvoiceGenerated(org string) {
	if c == nil || c.invoicesGenerated == nil {
		return
	}
	c.invoicesGenerated.WithLabelValues(normalizeOrg(org)).Inc()
}

// SetActiveSubscriptions updates the active subscription gauge for Cloud accounting.
func (c *CloudMetrics) SetActiveSubscriptions(org string, count int) {
	if c == nil || c.activeSubscriptions == nil {
		return
	}
	if count < 0 {
		count = 0
	}
	c.activeSubscriptions.WithLabelValues(normalizeOrg(org)).Set(float64(count))
}

// IncEngineError records a billing workflow error for Cloud accounting.
func (c *CloudMetrics) IncEngineError(org, operation string) {
	if c == nil || c.engineErrors == nil {
		return
	}
	c.engineErrors.WithLabelValues(normalizeOrg(org), normalizeLabel(operation)).Inc()
}

// Push sends metrics via the configured pusher. Callers must invoke this explicitly.
func (c *CloudMetrics) Push(ctx context.Context) error {
	if c == nil || c.pusher == nil || c.registry == nil {
		return nil
	}
	if ctx == nil {
		ctx = context.Background()
	}
	return c.pusher.Push(ctx, c.registry)
}

func normalizeOrg(org string) string {
	org = strings.TrimSpace(org)
	if org == "" {
		return "unknown"
	}
	return org
}

func normalizeLabel(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "unknown"
	}
	return value
}
